### ISSUE TITLE
Compare xml file with strings without id and value

### ISSUE THREAD

**Issue by bovirus** [rpeyron/xmltreenav#15]
iI have a file like this the files attached

[Language.zip](https://github.com/rpeyron/xmltreenav/files/10098201/Language.zip)

I want to compare this to find difference.

I tried different values for identifer (I tried onli value as @value and other) but without find the right value for compare

What are the right values in File compare window?

Thanks. KR.

**Comment by rpeyron** [comment]
xmlTreeNav compares nodes with the same tag name. Identifiers are used only to distinguish tags with the same tag names. In your files it seems there is no several tag names with the same name, so you should get a good result with what you tried or with no identifiers. Have you observed bad results with what you tried? (what I see is quite good)
