### ISSUE TITLE
Show strings available only in first file or second file

### ISSUE THREAD

**Issue by bovirus** [rpeyron/xmltreenav#5]
@rpeyron 

Please add the options to 

Show strings available ONLY in first file
Show strings available ONLY in second file
Show strings available ONLY in first file, second file and equal

Thanks.

**Comment by rpeyron** [comment]
This is already possible with customizable XSLT Displays

I have added more example that should be close to that in the default config files and xslt (https://github.com/rpeyron/xmltreenav/tree/master/bin/xslt - still need to be added in packages, should be done later)

**Comment by bovirus** [comment]
@rpeyron 

Thanks. If you can please update ,po fiel with new strings.

**Comment by rpeyron** [comment]
Done

**Comment by rpeyron** [comment]
Also please note that these are examples to be customized by the user, and the user is free to translate its customized commands in config.xml
