### ISSUE TITLE
Copy list of orphan strings into clipboard

### ISSUE THREAD

**Issue by bovirus** [rpeyron/xmltreenav#6]
@rpeyron 

Please add if you can the function to copy the string seelcted (ot html tag) in the clipboard.

Could be useful to make a search for orphan strings.

Or is it possoible to make a list and save it in text file about strings available ONLY inf first file and ONLY availbel in second file?

Could be usfuil for xml file alignemt.

Thanks.

**Comment by rpeyron** [comment]
Hello, 

1/ About the copy feature

The Edit / Copy menu (and Ctrl-C) will copy the selected XML node in the clipboard.

2/ About the list of modified elements

It is customizable with HTML XSLT Display. I have added an example in https://github.com/rpeyron/xmltreenav/blob/master/bin/xslt/html-lists.xsl

![image](https://user-images.githubusercontent.com/3126751/203133109-3e9de3c4-9f84-41a6-a497-d737a496c98e.png)

**Comment by bovirus** [comment]
@rpeyron 

Thanks. If you can please update ,po fiel with new strings.

**Comment by rpeyron** [comment]
Done
