### ISSUE TITLE
Windows installer - Modify script to include copy of .po file

### ISSUE THREAD

**Issue by bovirus** [rpeyron/xmltreenav#7]
@rpeyron 

In the windows installer maker script 

/master/build/win32)/XmlTreeNav.iss

currently there are the instructions to copy .mo file (compiled language file).

Source: ..\..\bin\lang\fr\xmlTreeNav.mo; DestDir: {app}/lang/fr; Flags: ignoreversion
Source: ..\..\bin\lang\it\xmlTreeNav.mo; DestDir: {app}/lang/it; Flags: ignoreversion

I propose you to modify it to include .po file

Source: ..\..\bin\lang\fr\xmlTreeNav.po; DestDir: {app}/lang/fr; Flags: ignoreversion
Source: ..\..\bin\lang\it\xmlTreeNav.po; DestDir: {app}/lang/it; Flags: ignoreversion

to have in language folder both .po and .mo file as it happen for portable version.

Thanks.

**Comment by rpeyron** [comment]
Why would .po files would be useful in the setup?  They are source files, not useful for runtime.

**Comment by bovirus** [comment]
@rpeyron 

If you want to edit or add a translation you need .po files.

The .po files is provided  with portable version.
Then why don't provide with installer version?

What are the negative point to include .po with installer version?

**Comment by rpeyron** [comment]
To edit&add translations you should always get files from upstream. The reference is this GitHub.  I guess this was included in the portable version when this GitHub did not exist.

**Comment by bovirus** [comment]
@rpeyron 
 
OK.
