### ISSUE TITLE
Change order of option - First removed then added elements

### ISSUE THREAD

**Issue by bovirus** [rpeyron/xmltreenav#8]
@rpeyron 

Hi.

Could you please change the menu order 

Display added
Dispaly removed
Display added and removed

in

Dispaly removed
Display added
Disaply removed and added

In this way show first the difference in first file then the difference in second file.
And the option are in order "show the difference in first fil"e and next option is "show differences in second file".

About to display first removed and after added could you probably change the content of the script.
Now seem viceversa

Plerase consider i  a menu decription likle

Display available only in first file
Display available only in second file
Dispaly available only in first and second file

could be describe easily the functions 

Thanks.

**Comment by rpeyron** [comment]
Hello, the configuration files I provided are only examples to make easier the customization by the user to meet its specific file structure, use cases and expectations. You may edit config.xml very easily to meet your need by re-ordering and updating the concerned lines.

**Comment by bovirus** [comment]
@rpeyron 

Before to write this I tried myself using current 

**filter-added-removed.xsl**

xsl:variable name="filter">*[@diff:status='added']|*[@diff:status='removed']|*[count(descendant::*[@diff:status='added' or @diff:status='removed']) &gt; 0]

in 

xsl:variable name="filter">*[@diff:status='removed']|*[@diff:status='added']|*[count(descendant::*[@diff:status='removed' or @diff:status='added']) &gt; 0]

invertinbg position of added removed but seems that didn't works.

Could you please help me to identify teh right value to use to get my scope?

Thanks.

**Comment by rpeyron** [comment]
Hello, as mentioned in my reply above, the file you need to edit to change the menu order is config.xml.

**Comment by bovirus** [comment]
@rpeyron 

Please help to identify teh right value for XLS.

I change the order

xsl:variable name="filter">[@diff:status='removed']|[@diff:status='added']|[count(descendant::[@diff:status='removed' or @diff:status='added']) > 0]

replacing added and removed order but it seems that didn't works.

Thanks.

**Comment by rpeyron** [comment]
I have missed that you wanted to change also the content of the script and not only the menu order. Please read my other comment in #9, you just have to change the order of the outputted html tables in the '/' template.

**Comment by bovirus** [comment]
As I explained I change the order

original 

<xsl:variable name="filter">*[@diff:status='added']|*[@diff:status='removed']|*[count(descendant::*[@diff:status='added' or @diff:status='removed']) &gt; 0]</xsl:variable>

new version

xsl:variable name="filter">[@diff:status='removed']|[@diff:status='added']|[count(descendant::[@diff:status='removed' or @diff:status='added']) > 0]

but it seems that didn't works.

**Comment by rpeyron** [comment]
Ok, sorry, didn't understand before reading #14 that you wanted to sort _in the tree view_. Not possible now. A little explanation about what you tried: In XPath syntax, `|` means "or", and it is used to filter the elements that match, but is won't sort them. Sorting in XSL has to be done with the tag [xsl:sort](https://www.w3schools.com/xml/xsl_sort.asp), and you can use that with an external XSL file or the HTML display XSLT, but not the customizable XSLT because of the way it works: it will perform an XSLT transform on each XML node to be displayed and will expect a result of the XSLT transform as below:

```xml
<node icon="the predefined icon to be displayed" children="the XPath expression to select the children nodes">the text to be displayed on the line of the element in the tree</node>
```

**Comment by bovirus** [comment]
@rpeyron 

Please don't consider the sort option.

What's the right  syntax to show as color icon befroe the elements added (red icon) and the the green icon (removed items)

Currently is viceversa.
Before the removed then added.

baecause for me is mroe logical if you compare two file (first is amster) teh second ex is translation. to see first added strings and after removed strings.

Thanks.

**Comment by rpeyron** [comment]
I don't understand what you want, neither the difference with what you asked in #14, neiher what you ask with icons (Elements added are represented with a green icon with a "+" on it, not a red icon), nor why workarounds mentioned in #14 are not suitable.
