### ISSUE TITLE
Create html list of differences about orphan in first/second file

### ISSUE THREAD

**Issue by bovirus** [rpeyron/xmltreenav#9]
@rpeyron 

Coudl you please add a filter to show a HTML list of only orhan strings in first and second file (removed and added elements) without elements that are available in both files (now tehse are included)?

It's very usuful to compare and align XML files.

Please show liast only about HTML ID (not value)

It's useful to align files.

Thanks.

**Comment by rpeyron** [comment]
Hello, the configuration files I provided are only examples to make easier the customization by the user to meet its specific file structure, use cases and expectations. You may edit xslt/html-list.xsl and config.xml very easily to meet your need by removing the lines related to the modified status you don't want.

**Comment by bovirus** [comment]
@rpeyron 

Before to write this I tried myself tto identify teh right parametr in 

**helper-default-filter.xsl**

to get my scope but I'm not able to do that.
Could you help me to identifdy what are the right parameter to get my scope?

I will add it at config.xml.

Thanks.

**Comment by rpeyron** [comment]
Hello,

As stated in my previous reply, the file you need to get inspiration from is "xslt/html-list.xsl" (and not helper-default-filter.xsl). You can identify the right file to look at first by reading the config.xml file ; you will see the line corresponding to the menu you want to adapt and read the corresponding file:

```xml
<display name="Display HTML Lists of differences" type="html" file="xslt/html-lists.xsl" />
```

The .xsl files are in XSLT language. If you are dealing with XML files, you sure should be interested in the amazing power of XSLT and XPath (here is a good tutorial [https://www.w3schools.com/xml/xsl_intro.asp] ; I guess there is many more now, but it was the one I used at the time of writing xmlTreeNav)

An  XSL file is a collection of "templates" that match certain XML nodes and define what to output on those nodes, For instance `match="/"` will match the root node and `match="*"` will match all other nodes.

As you want to remove the 'modified' section of the example, you have to spot the section that output that, and delete the corresponding lines:
```html
<h1>Modified</h1>
 <table>
 <tr><th>Id</th><th>Value</th></tr>
 <xsl:apply-templates select="//*[@diff:status='modified']" />
 </table>
```

Those lines are outputting in the root node template a "Modified" header with a table that will execute the other template for each element with the diff:status attribute equal to 'modified' (XPath syntax). If you need to customize the data outputted, you will modify this template:

```xml
<xsl:template match="*">
<tr>
 <td><xsl:value-of select="@id" /></td>
 <td><xsl:value-of select="@value" /></td>
</tr>
</xsl:template>
```

And replace @id and @value with the attributes names you need (or any other XPath) ; you can also add/remove column by using the same pattern.

Please update your repo before, as I fixed two duplicated lines in the example.

Hope this helps

**Comment by bovirus** [comment]
@rpeyron 

I tried to follow.

I remove the modified section.

<h1>Modified</h1>
 <table>
 <tr><th>Id</th><th>Value</th></tr>
 <xsl:apply-templates select="//*[@diff:status='modified']" />
 </table>

It's OK.

I want to show only id without value then I delete

 <td><xsl:value-of select="@value" /></td>

but the result is not what I expect.

Sure the error is mine but I didn't udnerstand thawhere.

**Comment by rpeyron** [comment]
To remove the values columns you have to :
1. in the "/" template, change the value headers to delete the value column in the table definition (one per table generated):
```html
<tr><th>Id</th><th>Value</th></tr>
```
should be modified to;
```html
<tr><th>Id</th></tr>
```

2. in the "*" template, remove the elements line in the table:
```html
 <td><xsl:value-of select="@value" /></td>
```
